name: App Deploy To Github Pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Generate Environment Variables File for Production1
        run: echo "REACT_APP_HOST=$REACT_APP_HOST">>.env.production
        
        env:
          REACT_APP_HOST: ${{ secrets.REACT_APP_HOST }}
          
      - name: Generate Environment Variables File for Production2
        run: echo "PUBLIC_URL=$PUBLIC_URL">>.env.production
        
        env:
          PUBLIC_URL: ${{ secrets.PUBLIC_URL }} 
          
      - name: Deploy react app to github pages
        uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
